version: '3'
services:
  web:
    image: nginx
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    volumes: 
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD