version: '3'
services:
  web:
    image: nginx
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    volumes: 
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes: 
      - ./pg/conf/:/etc/postgresql/:ro
      - ./pg/init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD